### ISSUE TITLE
Tracking Issue WR Model

### ISSUE THREAD

**Issue by CPLANT14** [CPLANT14/FF-Models#2]
**About**
Create a model that can be used to make tiebreaker decisions between similarly valued players
Simulate decisions between similarly ranked players by FantasyPros ECR

Ex. (https://docs.google.com/spreadsheets/d/10_z0iUCMMO8KoGtpiQglGhrxGCSu7iWQJku3LbToyD4/edit?gid=0#gid=0)

- [ ] Collect Data
- [ ] Use intuition to create simple models (YAC Score, Catch Score, Prod Score)
- [ ] Test simulated decision hit rates
- [ ] Create an overall score model, averaging the other simple models
